### ISSUE TITLE
Finer grained stability levels for affiliated packages

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#138]
One of the items of feedback that came from ADASS (specifically @cdeil mentioned it to me) is that we should probably have the equivalent of:

http://docs.astropy.org/en/stable/stability.html

for affiliated packages. The different levels I imagine are:
- In early development, very incomplete
- Partially stable, but still incomplete
- Stable, still some development
- Feature complete

We could use traffic-light colors (like in the core package) to show these in the affiliated package table.

**Comment by cdeil** [comment]
Just to give my 2 cents: this came out of the "small group discussion" from two people new to Astropy from our group.

If you use such levels, you could also consider re-using the standard Python classifiers instead of re-inventing new ones:
```
Development Status :: 1 - Planning
Development Status :: 2 - Pre-Alpha
Development Status :: 3 - Alpha
Development Status :: 4 - Beta
Development Status :: 5 - Production/Stable
Development Status :: 6 - Mature
Development Status :: 7 - Inactive
```

Personally I'm not sure if one such level is enough info for people to make decisions if / for what applications they could / should use a given package.
And keeping that status in sync and correct over the years might be difficult.

So just to offer an alternative: there could also be a paragraph or bullet list of things one can consider when evaluation a package and how to get that info:
- list of previous releases from PyPI
- development activity and number of contributors from Github
- who's maintaining it? do they give a point of contact? -> should be yes, and you can just write them and let them know what you want to do.

I think there's e.g. blog posts or other docs with info how to evaluate a give package. Maybe we could just link to a good one and keep our effort to document this low?

Some info (previous releases, GH stars, development status classifier) could be pulled automatically from `setup.py`, reducing effort to keep that affiliated package summary page up to date, and serving as a quality check that people are declaring basic info about their packages in the standard way for Python packages.

**Comment by taldcroft** [comment]
Excellent idea overall.

On the suggestion of  using the Python classifiers, while that is of course sensible, my feeling if that those classifiers are not immediately meaningful to a big fraction of our audience.  We could of course provide translations, but I really like the 4-colored dashboard.  

The one thing in the Python classifiers we are missing is `Inactive`, and that would be something to consider for affiliated packages.  Or more precisely provisional affiliated packages, since I think that any package which becomes inactive would be demoted to "provisional" or removed entirely.

About maintaining a list, it seems like the level of effort would not be *too* much of a burden.  In fact this could be a duty of the web maintainer role, or even a new role like affiliated package coordinator.  In short there are people who have expressed interest in working on astropy without having specific expertise.  Having a duty like "review and maintain affiliated package status on a yearly (or bi-annual?) basis" seems fine.  Recommendations for changes would be brought to the coordination committee.

👍 on providing a link or instructions on evaluating packages.

**Comment by bsipocz** [comment]
I really like this idea, thanks @cdeil for raising this.

However traffic lighting (especially flagging red) makes me a bit worried about scaring people off trying out some of the rapidly developing packages. I'm not sure how often an average user would check the status of packages again and again.

**Comment by astrofrog** [comment]
Good point about the colors - I think something like our current stability page (no red) would make more sense than actual traffic light colors.

**Comment by astrofrog** [comment]
We've done something along these lines in our [new review guidelines](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md)
