### ISSUE TITLE
Make a page with infrastructure packages

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#219]
Now that we've done some of the work of splitting out generically useful infrastructure packages, we really should do a good job of advertising them. I was thinking that we should maybe rename the top-level 'affiliated packages' page to just 'packages', and in there we could have the core package, the infrastructure packages, and the affiliated packages.

Infrastructure packages:

* astropy-helpers
* package-template
* ci-helpers
* sphinx-automodapi
* pytest-openfiles
* pytest-doctestplus
* pytest-astropy
* pytest-remotedata
* astropy-sphinx-theme

Am I missing any?

We could also mention somewhere:

* coordinates-benchmark
* astropy-benchmark

(but less important)

**Comment by bsipocz** [comment]
the new sphinx template

**Comment by bsipocz** [comment]
and the not yet existing sphinx-astropy

**Comment by bsipocz** [comment]
and maybe you want to list also pytest-arraydiff, though that was very much your effort on your own (and maybe pytest-mpl, but that's more logically belongs to mpl)

**Comment by bsipocz** [comment]
(and there are a few borderline ones, like astropy-docker, and astropy-data?)

**Comment by eteq** [comment]
I think it's important this be more than a "list of links" as we start making the helpers more a la carte. 

Because right now you get pretty much everything with the helpers, knowledge of good practices enabled by these tools sort of comes "for free" because template users see a thing and eventually try to figure out how it works. But in the goal of a la carte helpers we need a new mechanism... And this seems like the right place for it!

**Comment by pllim** [comment]
I like the sentiment but it would be just another page we will forget to update. Infrastructure is ever changing.

xref https://github.com/astropy/astropy-project/issues/118
