### ISSUE TITLE
Add role on team page for operations / development / devops support

### ISSUE THREAD

**Issue by embray** [astropy/astropy.github.com#393]
I don't know exactly what to call this role yet, or if it should be multiple roles.  This was suggested to me by @pllim and @bsipocz both of whom would fall under this category, as would I.  Opening an issue to discuss the scope of this role.

**Comment by bsipocz** [comment]
one, or multiple roles I would guess. Given the fragmentation of the page for other roles, these all should deserve their own category, unless of course people keeps insisting that, unlike social media, infrastructure is not important

**Comment by embray** [comment]
Some of the existing roles should probably be nested as sub-roles under some larger devops category.  E.g.:

* Documentation infrastructure maintainer
* Astropy-helpers maintainer
* Testing infrastructure maintainer
* Package template maintainer
* CI-helpers maintainer
* Distribution coordinator (?)

possibly others, plus new roles not already listed.

**Comment by bsipocz** [comment]
Roles being bloated up with names not doing the given roles is not helping either

> Distribution coordinator

should be cleaned up to contain names who work with astropy. Only two on that list gives any  feedback for packaging, bug reports and fixes

> Package template maintainer

there are 5 people listed, who is involved in and responsible for the template?

> Testing infrastructure maintainer

names are not accurate, again. There has been a ton of issues with the plugins due to new pytest releases in the past year, and the frustration was directed onto people who are not even on this list.

> Documentation infrastructure maintainer

names are not accurate

**Comment by bsipocz** [comment]
All of these above are well known and has been raised, at least at the coordination meeting last December. Nothing has changed since then.
(But it started before, see the motivation for my scipy talk last year, and my mediocre try to highlight the people who are actually behind these parts of the ecosystem)

**Comment by embray** [comment]
Perhaps it is time for a full auditing of the Team page (this could go hand-in-hand with other issues like #167, #183, #323).  I think updates like these could make the project seem more welcoming and encourage newcomers to want to take on large roles within the project. 

I will open a separate issue for such an auditing, and raise the issue on the mailing list.  This is also relevant to my plan to add better automation of issue/pr assignees based on component.

**Comment by bsipocz** [comment]
Good luck with that. The pushback for this from the CoCo big, as apparently everything is up to date with names. No wonder TomA's credit page didn't go ahead as it might have shown some discrepancies.

**Comment by astrofrog** [comment]
I’d be very much in favour of grouping infrastructure/devops roles under a common heading

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy.github.com/issues/393#issuecomment-687638618

Chopping it up too finely might be counter-productive. All these roles are filled by only a few of us anyway. So, I agree with Tom [above](https://github.com/astropy/astropy.github.com/issues/393#issuecomment-687651900).

I also agree with Brigitta that keeping the page accurate and updated is an ongoing problem, but that shouldn't stop us from accomplishing this issue.

**Comment by pllim** [comment]
p.s. I briefly thought about auto-populating Team page from GitHub activities, but then it will devolve into Battle Royale of GitHub metrics, which is even worse.

**Comment by bsipocz** [comment]
> I also agree with Brigitta that keeping the page accurate and updated is an ongoing problem

and the biggest issue is that roles are missing from the page. People spending significant time on the project are not listed on the page as they are generalists rather than sub-package owners, or they provide the overall oversight of devops and daily operation. No recognition but they face unsatisfaction all the time as their work is only ever noticed when parts of the CI stops working for reasons, most contributors never realize how much constant upkeep is necessary for a big library such as astropy before the components starts to rot away.

**Comment by embray** [comment]
See also my comment here: https://github.com/astropy/astropy.github.com/issues/323#issuecomment-689802741  Putting this information in a kind of database might help make it easier to keep up-to-date.

**Comment by astrofrog** [comment]
The docs and testing infrastructure maintainers are indeed very incomplete - for a start @bsipocz and @pllim should clearly be added to these roles. Maybe discussing how we want to organise and group the roles could be an agenda item of the first of the regular calls I was suggesting.

**Comment by astrofrog** [comment]
This was actually done (https://www.astropy.org/team.html#devops_team) so closing!
