### ISSUE TITLE
http://www.astropy.org/astroquery/

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy.github.com#505]
@keflavich - Today I wanted to astro-query SIMBAD and Google pointed me here: http://www.astropy.org/astroquery/

It looks like an old project landing page, still mostly up-to-date, but not really anything in addition to https://astroquery.readthedocs.io . Is it worth keeping / maintaining http://www.astropy.org/astroquery/ in addition to https://astroquery.readthedocs.io ? or maybe just remove http://www.astropy.org/astroquery/ and put a redirect to  https://astroquery.readthedocs.io ? 

One thing I noticed is that http://www.astropy.org/astroquery/ says it requires Astropy 0.4+, but https://astroquery.readthedocs.io says it requires Astropy 1.0+.

**Comment by eteq** [comment]
I gave more details in astropy/astropy-project#322, but I don't think this is possible if the desire is for 301- or 302-style redirects, because GitHub Pages doesn't seem to allow that.  I did offer an alternative in astropy/astropy-project#322 though (which I in fact already implemented) - see there for more discussion.

**Comment by bsipocz** [comment]
Hurray for closing 5 year old issues 🎉
