### ISSUE TITLE
Affiliated packages with pyOpenSci: Link to packages under review?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy.github.com#580]
This is a follow up of:

* #573 

Would it be useful to add a link to https://github.com/pyOpenSci/software-submission/issues?q=is%3Aissue+is%3Aopen+label%3Aastropy so people can see what are currently under review at pyOpenSci? Unless @lwasser has a better way?

cc @dhomeier @hamogu

**Comment by hamogu** [comment]
We *can* do that, but I'm not sure it's required. I'm not going to stop anyone from adding a link, but I can also think of more important things to do with our time.

**Comment by lwasser** [comment]
That is the best way @pllim  ✨ 
For reference: i'm working on a build that will allow us to update review status in real time on the website (creating a yaml file or json). However, it will take some time for that to be complete, tested working etc.

**Comment by pllim** [comment]
Okay, I'll just leave this issue open for a bit and see. It is certainly not urgent but if people start looking at our updated Affiliated page and get alarmed why the list is empty, then maybe we can throw this link in then.

**Comment by hamogu** [comment]
No. Packages have been affiliated before, are still affiliated now; they are not loosing this status now [*]. However, we do want to present the lists separately - some packages might even appear on both lists at some point.

*: However, we've always said that there should be an occasional re-review of packages with packages that become unmaintained loosing there affiliated status at some point. It's just that in practice the affiliated editors have never gotten to that point. I hope that, in collaboration with PyOpenSci, we'll get to do that in the coming years (starting with the oldest package at a rate of a few per year, so nobody gets reviewed more than once every 5-10 years.

**Comment by hamogu** [comment]
Maybe the best solution is just small rewording from "is currently empty" to "The list of affiliated packages is quite long and we thus split it in packages that have been reviewed by PyOpenSci starting March 2023 (below) and the packages that became affilated before MArch 2024 (list of 48 packages AT THIS LINK)"?

**Comment by bsipocz** [comment]
> list of 48 packages AT THIS LINK)

But those lived under the affiliated link for so many years, it kind of should be the other way around. Or both to be listed on the same, usual, link.

**Comment by bsipocz** [comment]
(And re-reviewing the status is totally different than sending them through a new process they haven't signed up for)

**Comment by pllim** [comment]
If "legacy" reflects negatively, we could change it to "pre_ape22" or something. Open to suggestions but I do want to keep it on a separate page to avoid clutter... #573 was opened for a while and posted on Slack and astropy-dev for comments.

**Comment by pllim** [comment]
Also maybe continue this concern on a new issue as it seems to be getting out of topic here? Thanks!

**Comment by hamogu** [comment]
> (And re-reviewing the status is totally different than sending them through a new process they haven't signed up for)

No, it's not. It's slightly different, but not much since the process is almost the same and the requirements are almost the same. But that's why we went through the APE process (incl notices on slack and astrop-dev) so that people who disagree had ample opportunity to comment. There is a whole section on "re-review" in APE 22.

**Comment by hamogu** [comment]
Having ~50 affiliated packages is still good! However, how it's displayed on the website has not evolved since we had 5 packages or so. A website that's easily readable with 5 package is not with 50. We could have split the page when we reach 30 affiliated packages or when we reached 40 affiliated packages or waited till we reach 100. There is obviously no exact number - but as the number grows (and continues to grow) we need to adjust how it's displayed on the page.

We could have done that independent of the pyopensci and APE22, but it just happens to be a good opportunity now because we need te edit the text anyway.

**Comment by pllim** [comment]
Just so everyone knows if I go quiet, I am about to take some time off. I will come back and address replies when I return. Thanks for your patience!

**Comment by hamogu** [comment]
That does not mean that text is perfect - it can obviously be changed - but there is a reason that listings on any website or listing (google, MAST, Chandra search form, ADS) typically output a limited number of results per page. We don't want to be that complicated, but splitting in some way makes sense to me.

**Comment by bsipocz** [comment]
Then a rephrasing is very timely, as currently the page states, before the empty table that "The following table lists all currently registered affiliated packages." all the while you claim that packages previously in the list didn't lose their affiliated status. Those are contradicting. So call those in the empty table affiliated with pyopensci, or similar, rather than adding extra, negative adjectives to those already affiliated.

And frankly, the ape was about the collaboration and offloading the editorial process, not that you banish the old listing. I fully agreed with the former and thus didn't follow the rest of the very very lengthy APE process, so now ending up with a practically hidden "legacy" page is not that great experience. And, no neither google, or chandra, or ads are returning empty results as opposed to ~50 like in this case and are listing all the stuff if you ask for it rather than dumping it into a hidden page linked under a `here` at best.

**Comment by pllim** [comment]
I will propose a follow-up PR to address the concerns that started around https://github.com/astropy/astropy.github.com/issues/580#issuecomment-2015417745 . Thank you for your patience.

**Comment by pllim** [comment]
Back to the original topic, ZodiPy has been accepted into pyOpenSci, are there other packages under review, @dhomeier or @hamogu ?

**Comment by pllim** [comment]
Ah, nvm... I see it here. https://github.com/pyOpenSci/software-submission/issues?q=is%3Aissue+is%3Aopen+label%3Aastropy
