### ISSUE TITLE
Grammatical Fixes in Contribution Guidelines

### ISSUE THREAD

**Issue by KavyaKolavasi1** [astropy/astropy.github.com#640]
### Description

The following issues found regarding documentation to contribute to Astropy. The issues were grammatical in two different circumstances.
1)	**Taking on a formal Project Role Section** – “or a coordination commitee member”. 
               a. The correct spelling here should be “committee”
2)	**For academics: How to justify your contribution Section** – “This sections aims to provides suggestions…”
               a. The correction here is “This section aims to provides suggestions…”

Link to Guide: https://www.astropy.org/contribute.html#reporting-issues

**Comment by pllim** [comment]
Thank you for catching these. If you want to be credited by Git for fixing these, you can open a pull request and modify https://github.com/astropy/astropy.github.com/blob/main/contribute.html yourself. Otherwise, I can also fix it for you but I don't know how to credit you properly. Please let me know your preference. Thanks!

**Comment by pllim** [comment]
Hello. Since I did not hear back and had some time, I fixed them in https://github.com/astropy/astropy.github.com/commit/dfd423e5e297019cca8afb11252a2f40ff8c0de7 as you suggested. Thank you again.

**Comment by KavyaKolavasi1** [comment]
Hello, apologies for the delayed response! Thank you so much for being able to fix this.
