### ISSUE TITLE
Split 'About' into 'About' and 'Community'

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy.github.com#76]
At the moment, the 'About' section has information about the license, credits, citing astropy, and some high level information about the project. I wonder whether we might consider splitting into:

* About:
  * High-level description
  * Citing Astropy
  * License
* Community:
  * Team
  * Code of conduct
  * Also include links to mailing lists for example

**Comment by eteq** [comment]
I guess I'm -0 to this.  My main concern is that I suspect *fewer* people will see the "community" stuff, because my feeling is that people are not that likely to have a reason to go to that part of the page.  In some sense, right now, "about" is a way of forcing people to see the author list and such when they want info about the project.

But that's not too strong of an opinion, hence the 0.

**Comment by eteq** [comment]
I think this has become irrelevant since the addition of the team section, so closing...

**Comment by astrofrog** [comment]
What about renaming Team to Community or People though? (to make it more open?)
